"""Generate Capstone 1 viva presentation as a .pptx file."""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

# ── Colour palette ────────────────────────────────────────────────────────────
DARK_BLUE  = RGBColor(0x0D, 0x1B, 0x2A)   # slide background
ACCENT     = RGBColor(0x00, 0xB4, 0xD8)   # headings / highlights
WHITE      = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_GREY = RGBColor(0xCC, 0xD6, 0xE0)
ORANGE     = RGBColor(0xFF, 0x6B, 0x35)

W, H = Inches(13.33), Inches(7.5)         # 16:9 widescreen


def _bg(slide, colour: RGBColor = DARK_BLUE) -> None:
    """Fill slide background with a solid colour."""
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = colour


def _box(slide, left, top, width, height, text, size=20, bold=False,
         colour=WHITE, align=PP_ALIGN.LEFT, italic=False):
    """Add a text box to the slide."""
    txb = slide.shapes.add_textbox(left, top, width, height)
    tf  = txb.text_frame
    tf.word_wrap = True
    p   = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size    = Pt(size)
    run.font.bold    = bold
    run.font.italic  = italic
    run.font.color.rgb = colour
    return txb


def _accent_bar(slide, top=Inches(1.15)):
    """Thin horizontal accent line under slide title."""
    bar = slide.shapes.add_shape(1, Inches(0.4), top, Inches(12.53), Pt(3))
    bar.fill.solid()
    bar.fill.fore_color.rgb = ACCENT
    bar.line.fill.background()


def _title(slide, text):
    _box(slide, Inches(0.4), Inches(0.25), Inches(12.5), Inches(0.85),
         text, size=32, bold=True, colour=ACCENT, align=PP_ALIGN.LEFT)
    _accent_bar(slide)


def _bullet_block(slide, top, items: list[tuple[str, str]], col=WHITE):
    """Render (label, detail) bullet pairs."""
    y = top
    for label, detail in items:
        _box(slide, Inches(0.6), y, Inches(12), Inches(0.35),
             f"▸  {label}", size=16, bold=True, colour=ACCENT)
        y += Inches(0.32)
        if detail:
            _box(slide, Inches(1.1), y, Inches(11.5), Inches(0.32),
                 detail, size=14, colour=LIGHT_GREY)
            y += Inches(0.32)
    return y


# ── Slides ────────────────────────────────────────────────────────────────────

def slide_title(prs):
    """Slide 1 — Title."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _box(sld, Inches(0.5), Inches(1.8), Inches(12.3), Inches(1.2),
         "Multi-Agent Data Assistant", size=44, bold=True,
         colour=WHITE, align=PP_ALIGN.CENTER)
    _box(sld, Inches(0.5), Inches(3.1), Inches(12.3), Inches(0.6),
         "Natural Language Analytics on TPC-H · Databricks",
         size=22, colour=ACCENT, align=PP_ALIGN.CENTER)
    _box(sld, Inches(0.5), Inches(3.85), Inches(12.3), Inches(0.45),
         "AI-08 Capstone 1  ·  REVA University (RACE)  ·  2026",
         size=16, colour=LIGHT_GREY, align=PP_ALIGN.CENTER)
    bar = sld.shapes.add_shape(1, Inches(4), Inches(3.65), Inches(5.33), Pt(3))
    bar.fill.solid(); bar.fill.fore_color.rgb = ACCENT; bar.line.fill.background()


def slide_problem(prs):
    """Slide 2 — Problem Statement."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Problem Statement")
    _bullet_block(sld, Inches(1.4), [
        ("Data locked behind SQL",
         "Business users cannot query Databricks without writing SQL — insights are delayed."),
        ("No access control on ad-hoc tools",
         "Existing BI tools expose all tables to all users, violating data governance policies."),
        ("Schema complexity",
         "TPC-H has 8 inter-related tables; even analysts struggle to write correct JOINs."),
        ("No quality gate",
         "SQL generated by GenAI tools is unvalidated — wrong answers go undetected."),
    ])


def slide_solution(prs):
    """Slide 3 — Proposed Solution."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Proposed Solution")
    _box(sld, Inches(0.5), Inches(1.35), Inches(12.3), Inches(0.5),
         "A multi-agent NL-to-SQL assistant that routes plain-English questions to specialised agents,\n"
         "enforces role-based access, and scores every response before display.",
         size=15, colour=LIGHT_GREY)
    _bullet_block(sld, Inches(2.2), [
        ("Ask in plain English", "No SQL knowledge required — type a business question, get a data answer."),
        ("Role-aware responses", "Each user role (Analyst / Finance / Executive) sees only permitted tables."),
        ("Self-correcting SQL", "Failed queries are automatically fixed by Claude Haiku (up to 2 retries)."),
        ("Confidence badge", "Every answer is scored 0–5 by an LLM-as-judge before the user sees it."),
    ])


def slide_architecture(prs):
    """Slide 4 — System Architecture."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "System Architecture")
    flow = (
        "User Question\n"
        "     │\n"
        "  Guardrail  ──── off-topic ────▶  Rejection (0 ms)\n"
        "     │\n"
        "  Intent Classifier  (keyword rules, 0 API calls)\n"
        "     │\n"
        " ┌───┴──────────────┬──────────────────┐\n"
        " ▼                  ▼                  ▼\n"
        "doc_lookup      kpi_compute        sql_query\n"
        "ChromaDB RAG    RAG + SQL          SQL Agent\n"
        "                formula extract    self-correction\n"
        "     └──────────────┴──────────────────┘\n"
        "                    │\n"
        "             Evaluator (LLM-as-judge 0–5)\n"
        "                    │\n"
        "             Streamlit UI  ·  Chart  ·  Badge"
    )
    _box(sld, Inches(0.8), Inches(1.3), Inches(11.5), Inches(5.8),
         flow, size=13, colour=LIGHT_GREY)


def slide_tech_stack(prs):
    """Slide 5 — Tech Stack."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Tech Stack")
    left_items = [
        ("Streamlit",        "Chat UI with role selector sidebar"),
        ("LangGraph",        "Typed StateGraph — explicit agent routing"),
        ("Claude Haiku",     "SQL generation + self-correction + evaluation"),
    ]
    right_items = [
        ("ChromaDB",         "Local vector store — PDF knowledge base"),
        ("Databricks",       "TPC-H dataset (samples.tpch) — live SQL execution"),
        ("pypdf",            "Section-based PDF chunking (~20 semantic chunks)"),
    ]
    y = Inches(1.4)
    for label, detail in left_items:
        _box(sld, Inches(0.5), y, Inches(5.8), Inches(0.3), f"▸  {label}", size=16, bold=True, colour=ACCENT)
        y += Inches(0.3)
        _box(sld, Inches(1.0), y, Inches(5.5), Inches(0.3), detail, size=13, colour=LIGHT_GREY)
        y += Inches(0.35)
    y = Inches(1.4)
    for label, detail in right_items:
        _box(sld, Inches(6.9), y, Inches(5.8), Inches(0.3), f"▸  {label}", size=16, bold=True, colour=ACCENT)
        y += Inches(0.3)
        _box(sld, Inches(7.4), y, Inches(5.5), Inches(0.3), detail, size=13, colour=LIGHT_GREY)
        y += Inches(0.35)


def slide_rbac(prs):
    """Slide 6 — RBAC."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Role-Based Access Control (RBAC)")
    _box(sld, Inches(0.5), Inches(1.35), Inches(12.3), Inches(0.4),
         "Schema sent to the LLM is filtered by role before prompt construction — the model never sees forbidden tables.",
         size=14, colour=LIGHT_GREY)
    headers = ["Role", "Allowed Tables", "Blocked From"]
    rows = [
        ["Analyst",   "orders, customer, nation, region",                    "lineitem, supplier, partsupp, part"],
        ["Finance",   "orders, lineitem, supplier, partsupp, nation, part",   "customer, region"],
        ["Executive", "All 8 tables",                                         "—"],
    ]
    col_x = [Inches(0.4), Inches(2.4), Inches(8.0)]
    col_w = [Inches(1.8), Inches(5.4), Inches(4.8)]
    y = Inches(2.0)
    for i, h in enumerate(headers):
        _box(sld, col_x[i], y, col_w[i], Inches(0.38), h, size=14, bold=True, colour=ACCENT)
    y += Inches(0.42)
    for row in rows:
        for i, cell in enumerate(row):
            _box(sld, col_x[i], y, col_w[i], Inches(0.55), cell, size=13, colour=WHITE)
        bar = sld.shapes.add_shape(1, Inches(0.4), y + Inches(0.56), Inches(12.5), Pt(1))
        bar.fill.solid(); bar.fill.fore_color.rgb = RGBColor(0x33, 0x44, 0x55)
        bar.line.fill.background()
        y += Inches(0.62)


def slide_key_features(prs):
    """Slide 7 — Key Features."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Key Features")
    _bullet_block(sld, Inches(1.4), [
        ("Dynamic Intent Routing",
         "Keyword classifier routes to doc_lookup / kpi_compute / sql_query — 0 API calls, ~0 ms."),
        ("KPI-Aware Classification",
         "Named KPIs (from PDF) bypass sql_override — 'what is total order count?' → kpi_compute."),
        ("Hybrid RAG + SQL (KPI Path)",
         "Formula extracted from ChromaDB, then fed into SQL generation — grounded in documentation."),
        ("Self-Correction Loop",
         "On SQL error, Claude Haiku is asked to fix — up to 2 retries before surfacing the error."),
        ("Inline LLM-as-Judge",
         "Every response scored 0–5 for relevance before display. RBAC violations auto-score 0/5."),
        ("Live Schema Pull",
         "Schema fetched from Databricks INFORMATION_SCHEMA at query time — no stale static files."),
    ])


def slide_uat(prs):
    """Slide 8 — UAT Results."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "UAT Results — 37 Test Cases")
    sections = [
        ("Doc Lookup",     "6/6",  "100%"),
        ("KPI Compute",    "4/4",  "100%"),
        ("SQL Query",      "6/6",  "100%"),
        ("Complex SQL",    "6/6",  "100%"),
        ("RBAC Blocks",    "4/4",  "100%"),
        ("Guardrail",      "5/5",  "100%"),
        ("Intent Edge",    "6/6",  "100%"),
    ]
    col_x = [Inches(0.5), Inches(5.5), Inches(9.5)]
    y = Inches(1.55)
    _box(sld, col_x[0], y, Inches(4.8), Inches(0.38), "Section",        size=14, bold=True, colour=ACCENT)
    _box(sld, col_x[1], y, Inches(3.5), Inches(0.38), "Pass / Total",   size=14, bold=True, colour=ACCENT)
    _box(sld, col_x[2], y, Inches(3.0), Inches(0.38), "Pass Rate",      size=14, bold=True, colour=ACCENT)
    y += Inches(0.44)
    for sec, score, pct in sections:
        _box(sld, col_x[0], y, Inches(4.8), Inches(0.4), sec,   size=14, colour=WHITE)
        _box(sld, col_x[1], y, Inches(3.5), Inches(0.4), score, size=14, colour=WHITE)
        _box(sld, col_x[2], y, Inches(3.0), Inches(0.4), pct,   size=14, bold=True, colour=ACCENT)
        y += Inches(0.42)
    y += Inches(0.1)
    _box(sld, Inches(0.5), y, Inches(12.3), Inches(0.4),
         "Intent Accuracy: 37/37 = 100%   ·   Answer Accuracy: 31/31 = 100%",
         size=15, bold=True, colour=ORANGE, align=PP_ALIGN.CENTER)


def slide_differentiators(prs):
    """Slide 9 — Differentiators vs AI-07."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Differentiators vs Prior Work (AI-07)")
    headers = ["Dimension", "AI-07 (Ganesh Rohan)", "AI-08 (This Project)"]
    rows = [
        ["Architecture",  "Single pipeline",           "Multi-agent LangGraph StateGraph"],
        ["Access Control","None",                       "RBAC — schema filtered per role"],
        ["Schema Source", "Static files",               "Live Databricks INFORMATION_SCHEMA"],
        ["Knowledge Base","Schema docs only",           "PDF metrics + data dictionary (RAG)"],
        ["Quality Gate",  "Syntax match only",          "LLM-as-judge 0–5 badge + offline eval"],
        ["SQL Reliability","No error handling",         "Self-correction loop (2 retries)"],
    ]
    col_x = [Inches(0.4), Inches(3.6), Inches(8.0)]
    col_w = [Inches(3.0), Inches(4.2), Inches(5.2)]
    y = Inches(1.5)
    for i, h in enumerate(headers):
        _box(sld, col_x[i], y, col_w[i], Inches(0.38), h, size=13, bold=True, colour=ACCENT)
    y += Inches(0.44)
    for row in rows:
        _box(sld, col_x[0], y, col_w[0], Inches(0.42), row[0], size=12, bold=True, colour=WHITE)
        _box(sld, col_x[1], y, col_w[1], Inches(0.42), row[1], size=12, colour=LIGHT_GREY)
        _box(sld, col_x[2], y, col_w[2], Inches(0.42), row[2], size=12, colour=ACCENT)
        y += Inches(0.46)


def slide_demo(prs):
    """Slide 10 — Live Demo."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Live Demo")
    demos = [
        ("UC1 — KPI Definition",     "Analyst · 'What is Average Order Value?'  →  doc_lookup · badge 5/5"),
        ("UC2 — KPI Computation",    "Finance · 'What is Average Days to Ship for Q3 1996?'  →  kpi_compute"),
        ("UC3 — NL-SQL Query",       "Finance · 'What was total revenue by nation last year?'  →  sql_query · 25 rows"),
        ("UC4 — RBAC Block",         "Analyst · 'What was total revenue by nation?'  →  🔴 Blocked · badge 0/5"),
        ("UC5 — Guardrail",          "Any role · 'Who is the president?'  →  out_of_scope rejection · 0 ms"),
    ]
    y = Inches(1.55)
    for label, detail in demos:
        _box(sld, Inches(0.6), y, Inches(12), Inches(0.34), label, size=15, bold=True, colour=ACCENT)
        y += Inches(0.32)
        _box(sld, Inches(1.1), y, Inches(11.5), Inches(0.34), detail, size=13, colour=LIGHT_GREY)
        y += Inches(0.4)


def slide_future(prs):
    """Slide 11 — Future Scope & Conclusion."""
    sld = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(sld)
    _title(sld, "Future Scope & Conclusion")
    _box(sld, Inches(0.5), Inches(1.35), Inches(5.9), Inches(0.38),
         "Future Enhancements", size=17, bold=True, colour=ACCENT)
    future = [
        "Unity Catalog RBAC integration",
        "Confluence / SharePoint ingestion",
        "RAGAS automated evaluation",
        "User feedback loop for prompt tuning",
        "Streaming responses via Streamlit",
    ]
    y = Inches(1.85)
    for item in future:
        _box(sld, Inches(0.7), y, Inches(5.7), Inches(0.35), f"•  {item}", size=14, colour=LIGHT_GREY)
        y += Inches(0.38)
    _box(sld, Inches(6.9), Inches(1.35), Inches(6.0), Inches(0.38),
         "Conclusion", size=17, bold=True, colour=ACCENT)
    conclusion = (
        "This system demonstrates that a multi-agent architecture with "
        "role-aware RAG, live schema integration, and an inline quality gate "
        "can reliably bridge the gap between business users and enterprise data — "
        "achieving 100% intent accuracy and 100% answer accuracy across 37 UAT test cases."
    )
    _box(sld, Inches(6.9), Inches(1.85), Inches(6.0), Inches(3.5),
         conclusion, size=14, colour=LIGHT_GREY)
    _box(sld, Inches(0.5), Inches(6.5), Inches(12.3), Inches(0.6),
         "Thank you  ·  Questions Welcome",
         size=22, bold=True, colour=WHITE, align=PP_ALIGN.CENTER)


# ── Main ──────────────────────────────────────────────────────────────────────

def generate(output: str = "Capstone1_Presentation.pptx") -> None:
    """Build and save the presentation."""
    prs = Presentation()
    prs.slide_width  = W
    prs.slide_height = H

    slide_title(prs)
    slide_problem(prs)
    slide_solution(prs)
    slide_architecture(prs)
    slide_tech_stack(prs)
    slide_rbac(prs)
    slide_key_features(prs)
    slide_uat(prs)
    slide_differentiators(prs)
    slide_demo(prs)
    slide_future(prs)

    prs.save(output)
    print(f"Saved: {output}  ({len(prs.slides)} slides)")


if __name__ == "__main__":
    generate()
