"""Classify user questions into one of three intents using keyword matching — no API calls."""

import json
import os
import re

from agents.state import AgentState

_KPI_NAMES_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "kpi_names.json")


def _load_kpi_names() -> list[str]:
    """Load KPI names from data/kpi_names.json generated by data/ingest.py."""
    try:
        with open(_KPI_NAMES_PATH) as f:
            return json.load(f)
    except FileNotFoundError:
        return []

DOC_KEYWORDS: list[str] = [
    "what is", "what was", "define", "definition", "how is",
    "what does", "explain", "meaning of", "describe",
    "how ",          # catches "how X is calculated?" — "how many" is overridden by SQL_OVERRIDE
    "is calculated", "is computed", "is derived",
]

# Subset of doc keywords that strongly signal a definition request.
# Used to route "how is total order count calculated?" → doc_lookup even when a KPI name matches.
DEFINITION_KEYWORDS: list[str] = [
    "what is", "what was",
    "define", "definition", "explain", "meaning of", "describe",
    "what does", "how is", "is calculated", "is computed", "is derived",
]

# Strong SQL indicators — force sql_query when no KPI name is matched.
SQL_OVERRIDE_KEYWORDS: list[str] = [
    "total", "count", "sum", "how many", "show me", "list",
    "per", "by nation", "by region", "by segment", "by year", "by month",
    "top", "rank", "group", "aggregate", "compare",
    "trend", "monthly", "quarterly", "yearly", "over time",
]

# Time qualifiers that indicate the user wants a computed value, not a definition.
TIME_QUALIFIERS: list[str] = [
    "for q1", "for q2", "for q3", "for q4",
    "in 199", "in 200",          # catches "in 1995", "in 2003", etc.
    "for 19", "for 20",          # catches "for 1995", "for 2003", etc.
    "last year", "last quarter", "last month",
    "this year", "this quarter", "this month",
    "for year", "for month",
    "between", "from ", "since",
    "ytd", "year to date",
]

# Loaded from data/kpi_names.json, which is auto-generated by data/ingest.py.
# Checked before sql_override so "what is total order count?" → kpi_compute, not sql_query.
KPI_NAMES: list[str] = _load_kpi_names()


def _word_match(kw: str, text: str) -> bool:
    """Substring match for multi-word phrases; word-boundary match for single words."""
    if " " in kw:
        return kw in text
    return bool(re.search(r"\b" + re.escape(kw) + r"\b", text))


def classify_intent(state: AgentState) -> AgentState:
    """Set state['intent'] to doc_lookup | kpi_compute | sql_query."""
    question = state["question"].lower()

    has_kpi        = any(kw in question for kw in KPI_NAMES)
    has_definition = any(kw in question for kw in DEFINITION_KEYWORDS)
    has_doc        = any(kw in question for kw in DOC_KEYWORDS)
    has_sql        = any(_word_match(kw, question) for kw in SQL_OVERRIDE_KEYWORDS)
    has_time       = any(tq in question for tq in TIME_QUALIFIERS)

    if has_kpi and has_definition and not has_time:
        # "what is average order value?" / "how is AOV calculated?" → definition, no time filter
        intent = "doc_lookup"
    elif has_kpi:
        # "what is total order count?" → named KPI, compute it (with or without time filter)
        intent = "kpi_compute"
    elif has_sql:
        intent = "sql_query"
    elif has_doc and has_time:
        intent = "kpi_compute"
    elif has_doc:
        intent = "doc_lookup"
    else:
        intent = "sql_query"

    return {**state, "intent": intent}
